packages:
  - packages/**
  - docs
  - demo/*
  - e2e/**
  - test

catalog:
  '@better-fetch/fetch': 1.1.18
  better-call: 1.0.26
  tsdown: ^0.16.2
  typescript: ^5.9.3
  vitest: 3.2.4

catalogs:
  react18:
    '@types/react': ^19.2.3
    '@types/react-dom': ^19.2.2
    react: 19.2.0
    react-dom: 19.2.0

neverBuiltDependencies: []
